# Set the font and size
font_family      FiraCode
font_size        11.0

# Set background opacity (1.0 is fully opaque, 0.0 is fully transparent)
background_opacity 1.00

# Set the color scheme (optional)
include dracula.conf

# Remove window margin for a cleaner look
single_window_margin_width 0

# Set default shell (optional)
shell /usr/bin/bash

# Set tab bar style
tab_bar_style powerline
tab_powerline_style slanted
